### ISSUE TITLE
ヘッダーのviewの崩れの可能性があります💦

### ISSUE THREAD

**Issue by tiphp452** [tiphp452/freemarket_sample_58a_night#22]
下記の記述をコピペして試したところ、ユーザー登録画面のヘッダー部分でviewが崩れます。。。
改善案：headerタグにclass命名して個別にcssを当てる
https://github.com/tiphp452/freemarket_sample_58a_night/blob/bd75127a02b163162a5a9049874cdc7032454856/app/assets/stylesheets/modules/_header.scss#L9-L16
[![Image from Gyazo](https://i.gyazo.com/c4e98fba564e21c8cfbe6b87f2cf5159.png)](https://gyazo.com/c4e98fba564e21c8cfbe6b87f2cf5159)

**Comment by kouyama0201** [comment]
了解です💦
こちらの方で記述を直すので田中さんのファイルはそのままで大丈夫です🙇‍♂️
